services:
  db:
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    ports:
      - 5433:5432
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
      env_file: ./backend/.env


