services:
  web:
    build:
      context: .
      dockerfile: DockerFile
    volumes:
      - ./:/app
      - ./data:/app/data
    ports:
      - '8000:8000'
    env_file:
      - .env
    command: >
      uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload