services:
  db:
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
      - ./data/backup.sql:/docker-entrypoint-initdb.d/backups.sql
    ports:
      - "5433:5432"
  backend:
    build:
      context: .
      dockerfile: /backend/Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend




